### ISSUE TITLE
2x2 widget has some text overlap

### ISSUE THREAD

**Issue by jcvernaleo** [jholdstock/DecredWidgets#5]
When using the smallest (2x2) with a single item in it, the box on the write overlaps with the date (on a Pixel running the latest android).

**Comment by jcvernaleo** [comment]
![screenshot_20170615-085729](https://user-images.githubusercontent.com/768163/27182341-ced008ac-51a8-11e7-862b-789f07aec3c3.png)

**Comment by jcvernaleo** [comment]
@jholdstock is this project pretty much dead?  If so I'm going to close this issue (but I'll leave open if you think there is a chance you'll get back to it.

**Comment by jholdstock** [comment]
Hey John, hope you are well. I don't think I will ever get around to fixing this so you might as well close it.

Thanks

**Comment by jcvernaleo** [comment]
Kind of what I figured but I like to check before closing issues (and just trying to clean up my github a little).

And yeah, all is well.
